### ISSUE TITLE
Please update this plugin to statamic 5 [SC-1447]

### ISSUE THREAD

**Issue by Oleafeon** [Story-Chief/statamic-3-addon#7]

**Comment by bastiaandewaele** [comment]
@Oleafeon, we are currently working on the upgrade to Statamic 5.

**Comment by gregory-claeyssens** [comment]
@Oleafeon support for Statamic 5 (and 4) has been added in [version 1.0.8](https://github.com/Story-Chief/statamic-storychief/releases/tag/1.0.8)
